/**
 * @fileoverview Core type definitions for the open-multi-agent orchestration framework.
 *
 * All public types are exported from this single module. Downstream modules
 * import only what they need, keeping the dependency graph acyclic.
 */

import type { ZodSchema } from 'zod'
import type { SupportedProvider } from './llm/adapter.js'
import type { SchedulingStrategy } from './orchestrator/scheduler.js'

// ---------------------------------------------------------------------------
// Content blocks
// ---------------------------------------------------------------------------

/** Plain-text content produced by a model or supplied by the user. */
export interface TextBlock {
  readonly type: 'text'
  readonly text: string
}

/** Provider-native reasoning / thinking content emitted alongside normal text. */
export interface ReasoningBlock {
  readonly type: 'reasoning'
  readonly text: string
  /**
   * Provider-issued signature proving the reasoning was generated by the
   * model. Used by:
   *   - Anthropic / Bedrock: required to echo back unchanged on the next
   *     turn to continue a multi-turn tool-use conversation with extended
   *     thinking; the API rejects edited or missing signatures.
   *   - Gemini 3: optional `thoughtSignature` attached to thought-summary
   *     Parts; recommended to round-trip per Gemini docs ("always pass all
   *     signatures back as received") but not strictly required.
   * Absent for providers that don't sign reasoning (Gemini 2.5 thought
   * summaries, OpenAI o-series) and for reasoning that originated outside
   * the provider being addressed.
   */
  readonly signature?: string
  /**
   * Opaque encrypted thinking content returned by Anthropic when its safety
   * system blocks the raw reasoning text. The block must still be echoed
   * back on subsequent turns to satisfy the protocol, but its contents are
   * not human-readable. Carried separately from `text` because the wire
   * format for redacted blocks is distinct (`redacted_thinking` vs
   * `thinking`).
   */
  readonly redactedData?: string
  /**
   * Name of the {@link LLMAdapter} that produced this block, stamped at
   * extraction time on the native-to-IR path (both `chat` responses and
   * streaming final payloads). Consumed by outbound IR-to-native conversion
   * to decide between native echo and the `<thinking>` text fallback for
   * adapters whose {@link LLMAdapter.capabilities.echoesReasoning} is
   * `'own-issued'`.
   *
   * Typed as `string` rather than `SupportedProvider` so third-party adapter
   * implementations can stamp their own adapter name without modifying the
   * core enum.
   *
   * Optional for backwards compatibility with externally constructed IR.
   * Outbound paths treat `undefined` as "unknown provenance → cannot
   * native-echo".
   */
  readonly provenance?: string
}

/**
 * A request by the model to invoke a named tool with a structured input.
 * The `id` is unique per turn and is referenced by {@link ToolResultBlock}.
 */
export interface ToolUseBlock {
  readonly type: 'tool_use'
  readonly id: string
  readonly name: string
  readonly input: Record<string, unknown>
  /**
   * Provider-issued signature attached to a tool call to prove the call was
   * generated under extended thinking. Currently only used by Gemini
   * (`thoughtSignature`), which is a top-level field on the Part containing
   * the functionCall — an asymmetry from Anthropic, which signs the
   * preceding {@link ReasoningBlock} instead. Echo back unchanged on
   * subsequent turns to satisfy Gemini 3+'s strict validation.
   */
  readonly signature?: string
}

/**
 * The result of executing a tool, keyed back to the originating
 * {@link ToolUseBlock} via `tool_use_id`.
 */
export interface ToolResultBlock {
  readonly type: 'tool_result'
  readonly tool_use_id: string
  readonly content: string
  readonly is_error?: boolean
}

/** A base64-encoded image passed to or returned from a model. */
export interface ImageBlock {
  readonly type: 'image'
  readonly source: {
    readonly type: 'base64'
    readonly media_type: string
    readonly data: string
  }
}

/** Union of all content block variants that may appear in a message. */
export type ContentBlock = ReasoningBlock | TextBlock | ToolUseBlock | ToolResultBlock | ImageBlock

// ---------------------------------------------------------------------------
// LLM messages & responses
// ---------------------------------------------------------------------------

/**
 * A single message in a conversation thread.
 * System messages are passed separately via {@link LLMChatOptions.systemPrompt}.
 */
export interface LLMMessage {
  readonly role: 'user' | 'assistant'
  readonly content: ContentBlock[]
}

/** Context management strategy for long-running agent conversations. */
export type ContextStrategy =
  | { type: 'sliding-window'; maxTurns: number }
  | { type: 'summarize'; maxTokens: number; summaryModel?: string }
  | {
      type: 'compact'
      /** Estimated token threshold that triggers compaction. Compaction is skipped when below this. */
      maxTokens: number
      /** Number of recent turn pairs (assistant+user) to keep intact. Default: 4. */
      preserveRecentTurns?: number
      /** Minimum chars in a tool_result content to qualify for compaction. Default: 200. */
      minToolResultChars?: number
      /** Minimum chars in an assistant text block to qualify for truncation. Default: 2000. */
      minTextBlockChars?: number
      /** Maximum chars to keep from a truncated text block (head excerpt). Default: 200. */
      textBlockExcerptChars?: number
    }
  | {
    type: 'custom'
    /**
     * Compaction callback. Invoked before every LLM turn including the first,
     * so implementations that should only fire past a token threshold must
     * self-gate inside this function.
     */
    compress: (
      messages: LLMMessage[],
      estimatedTokens: number,
    ) => Promise<LLMMessage[]> | LLMMessage[]
  }

/** Token accounting for a single API call. */
export interface TokenUsage {
  readonly input_tokens: number
  readonly output_tokens: number
}

// ---------------------------------------------------------------------------
// Run identity and outcome
// ---------------------------------------------------------------------------

/** Scalar trace attribute values supported by the v2 record schema. */
export type TraceAttributeValue =
  | string
  | number
  | boolean
  | readonly string[]
  | readonly number[]
  | readonly boolean[]

/** Stable identity for one logical run and its current execution attempt. */
export interface RunIdentity {
  /** Logical run identifier. Preserved across checkpoint restore. */
  readonly runId: string
  /** One-based execution attempt. Incremented by each restore. */
  readonly attempt: number
  /** W3C-compatible 32-character lowercase hexadecimal trace identifier. */
  readonly traceId: string
  /** W3C-compatible 16-character lowercase hexadecimal root span identifier. */
  readonly rootSpanId: string
  /** Continuation links, currently used by checkpoint restore. */
  readonly links?: readonly TraceLink[]
}

/** A relationship from this execution attempt to an earlier trace. */
export interface TraceLink {
  readonly traceId: string
  readonly spanId: string
  readonly relation: 'continued_from' | 'depends_on' | 'consumed' | 'delegated_from'
  readonly attributes?: Readonly<Record<string, TraceAttributeValue>>
}

/** Backwards-compatible identity-specific alias for {@link TraceLink}. */
export type RunIdentityLink = TraceLink

/** Caller-provided identity controls shared by all top-level execution APIs. */
export interface RunIdentityOptions {
  /** Optional logical run identifier (1-128 characters). */
  readonly runId?: string
  /**
   * Per-run metadata, e.g. promptVersion / experiment / datasetTag.
   * Validated, written to root span attributes as `oma.meta.<key>`,
   * and echoed on the run result.
   */
  readonly metadata?: Readonly<Record<string, TraceAttributeValue>>
}

/** Per-call options for {@link OpenMultiAgent.runAgent}. */
export interface RunAgentOptions extends RunIdentityOptions {
  readonly abortSignal?: AbortSignal
}

export type RunStatusCode =
  | 'ok'
  | 'error'
  | 'cancelled'
  | 'timeout'
  | 'budget_exhausted'
  | 'rejected'
  | 'skipped'

/** Normalised top-level outcome. */
export interface RunStatus {
  readonly code: RunStatusCode
  readonly message?: string
}

export type TraceErrorKind =
  | 'provider'
  | 'tool'
  | 'framework'
  | 'callback'
  | 'validation'
  | 'timeout'
  | 'cancellation'
  | 'budget'
  | 'store'
  | 'exporter'
  | 'unknown'

/** JSON-safe, redacted error details for results and future trace records. */
export interface StructuredTraceError {
  readonly kind: TraceErrorKind
  readonly code?: string
  readonly name?: string
  readonly message?: string
  readonly retryable?: boolean
  readonly httpStatus?: number
  readonly provider?: string
  readonly attempt?: number
}

/** Additive result fields introduced by Observability v2. */
export interface RunOutcomeFields {
  /**
   * Runtime results always include this field. It is optional in the first
   * compatible 1.x type release so existing hand-written result fixtures keep
   * compiling; it can become required in a later compatibility window.
   */
  readonly identity?: RunIdentity
  /** Runtime results always include this field; see {@link identity}. */
  readonly status?: RunStatus
  readonly errorInfo?: StructuredTraceError
  /** Echo of validated metadata; present at runtime whenever the caller provided it. */
  readonly metadata?: Readonly<Record<string, TraceAttributeValue>>
  /** Additive, machine-readable execution warnings attached by the runtime. */
  readonly flags?: readonly RunFlag[]
  /**
   * True when an opt-in consequential-tool guard stopped a tool call because
   * no application approval gate was available. Re-run with an `onToolCall`
   * gate that returns `allow` to approve the call, or `deny` to reject it.
   */
  readonly confirmationRequired?: boolean
}

/** Machine-readable warnings that describe how a run was governed. */
export type RunFlag =
  | 'consequential-no-independence'
  | 'governance-overridden'
  | 'review-skipped-due-to-budget'

/** Context passed to user-supplied cost estimators. */
export interface CostEstimateContext {
  /** Agent whose LLM usage is being costed. */
  readonly agentName: string
  /** Model identifier used for the LLM call. */
  readonly model: string
  /** Provider used for the LLM call, when known. */
  readonly provider?: SupportedProvider
  /** Execution phase that produced this usage. */
  readonly phase: 'agent' | 'short-circuit' | 'coordinator' | 'worker' | 'synthesis' | 'consensus' | 'delegated'
  /** Task ID associated with the usage, when usage came from a task. */
  readonly taskId?: string
}

/** Normalised response returned by every {@link LLMAdapter} implementation. */
export interface LLMResponse {
  readonly id: string
  readonly content: ContentBlock[]
  readonly model: string
  readonly stop_reason: string
  readonly usage: TokenUsage
}

// ---------------------------------------------------------------------------
// Streaming
// ---------------------------------------------------------------------------

/**
 * A discrete event emitted during streaming generation.
 *
 * - `text`        — incremental text delta
 * - `reasoning`   — incremental reasoning / thinking delta
 * - `tool_use`    — the model has begun or completed a tool-use block
 * - `tool_result` — a tool result has been appended to the stream
 * - `budget_exceeded` — token budget threshold reached for this run
 * - `done`        — the stream has ended; `data` is the final {@link LLMResponse}
 * - `error`       — an unrecoverable error occurred; `data` is an `Error`
 */
export interface StreamEvent {
  readonly type: 'text' | 'reasoning' | 'tool_use' | 'tool_result' | 'loop_detected' | 'budget_exceeded' | 'done' | 'error'
  readonly data: unknown
  /**
   * Normalized failure metadata for an `error` event when its source is known.
   * This lets orchestrators distinguish a provider failure from a callback or
   * framework failure without inferring the source from the error text.
   */
  readonly errorInfo?: StructuredTraceError
}

// ---------------------------------------------------------------------------
// Tool definitions
// ---------------------------------------------------------------------------

/** The serialisable tool schema sent to the LLM provider. */
export interface LLMToolDef {
  readonly name: string
  readonly description: string
  /** JSON Schema object describing the tool's `input` parameter. */
  readonly inputSchema: Record<string, unknown>
}

/**
 * Context injected into every tool execution.
 *
 * Both `abortSignal` and `abortController` are provided so that tools and the
 * executor can choose the most ergonomic API for their use-case:
 *
 * - Long-running shell commands that need to kill a child process can use
 *   `abortController.signal` directly.
 * - Simple cancellation checks can read `abortSignal?.aborted`.
 *
 * When constructing a context, set `abortController` and derive `abortSignal`
 * from it, or provide both independently.
 */
export interface ToolUseContext {
  /** High-level description of the agent invoking this tool. */
  readonly agent: AgentInfo
  /** Team context, present when the tool runs inside a multi-agent team. */
  readonly team?: TeamInfo
  /**
   * Convenience reference to the abort signal.
   * Equivalent to `abortController?.signal` when an `abortController` is set.
   */
  readonly abortSignal?: AbortSignal
  /**
   * Full abort controller, available when the caller needs to inspect or
   * programmatically abort the signal.
   * Tools should prefer `abortSignal` for simple cancellation checks.
   */
  readonly abortController?: AbortController
  /**
   * Working directory for filesystem-tool sandboxing.
   *
   * - `string` — built-in filesystem tools (`file_read`, `file_write`,
   *   `file_edit`, `grep`, `glob`) require absolute paths and reject paths
   *   that resolve outside this directory (including via symlinks).
   * - `null` — sandbox is explicitly disabled; tools accept arbitrary paths.
   * - `undefined` — falls back to `<process.cwd()>/.agent-workspace`, an
   *   auto-created sandbox subdirectory (sandbox enabled).
   */
  readonly cwd?: string | null
  /** Arbitrary caller-supplied metadata (session ID, request ID, etc.). */
  readonly metadata?: Readonly<Record<string, unknown>>
  /** Run ID associated with this tool call, when available. */
  readonly runId?: string
  /** Task ID associated with this tool call, when available. */
  readonly taskId?: string
  /**
   * Per-agent scoped secrets for tool code to consume (API tokens, service
   * keys, etc.), sourced from {@link AgentConfig.credentials}. A tool reads
   * `context.credentials?.STRIPE_KEY` instead of closing over a module-level
   * secret, so each agent holds only the credentials it was assigned — a
   * compromised or misbehaving subagent cannot reach another agent's secrets.
   *
   * This is an ergonomic scoping seam, not an isolation boundary: tool code
   * still runs in-process and can read `process.env`. Values are treated as
   * secrets — the `credentials` key is auto-redacted from traces and
   * dashboards (see `utils/redaction.ts`).
   */
  readonly credentials?: Readonly<Record<string, string>>
}

/** Minimal descriptor for the agent that is invoking a tool. */
export interface AgentInfo {
  readonly name: string
  readonly role: string
  readonly model: string
}

/** Context passed to the optional per-call tool gate. */
export interface ToolCallContext {
  readonly toolName: string
  readonly input: Record<string, unknown>
  readonly agentName: string
  /** True when the registered tool definition declares real side effects. */
  readonly consequential?: boolean
  readonly runId?: string
  readonly taskId?: string
}

/** Decision returned by the optional per-call tool gate. */
export type ToolCallDecision =
  | { readonly action: 'allow' }
  | { readonly action: 'deny'; readonly reason?: string }

/** Optional middleware invoked after input validation and before tool execution. */
export type ToolCallGate = (context: ToolCallContext) => ToolCallDecision | Promise<ToolCallDecision>

/** Metadata attached to tool results when a per-call gate runs. */
export interface ToolCallGateMetadata {
  readonly action: ToolCallDecision['action']
  readonly reason?: string
}

/**
 * Minimal pool surface used by `delegate_to_agent` to detect nested-run capacity.
 * {@link AgentPool} satisfies this structurally via {@link AgentPool.availableRunSlots}.
 */
export interface DelegationPoolView {
  readonly availableRunSlots: number
}

/** Descriptor for a team of agents (orchestrator-injected into tool context). */
export interface TeamInfo {
  readonly name: string
  readonly agents: readonly string[]
  /** When the team has shared memory enabled; used for delegation audit writes. */
  readonly sharedMemory?: MemoryStore
  /** Zero-based depth of nested delegation from the root task run. */
  readonly delegationDepth?: number
  readonly maxDelegationDepth?: number
  readonly delegationPool?: DelegationPoolView
  /**
   * Ordered chain of agent names from the root task to the current agent.
   * Used to block `A -> B -> A` cycles before they burn turns against `maxDelegationDepth`.
   */
  readonly delegationChain?: readonly string[]
  /**
   * Run another roster agent to completion and return its result.
   * Only set during orchestrated pool execution (`runTeam` / `runTasks`).
   */
  readonly runDelegatedAgent?: (
    targetAgent: string,
    prompt: string,
    /** Internal OBS-1B parent handle; callers should omit it. */
    traceParent?: unknown,
  ) => Promise<AgentRunResult>
}

/**
 * Optional side-channel metadata a tool may attach to its result.
 * Not shown to the LLM — the runner reads it for accounting purposes.
 */
export interface ToolResultMetadata {
  /**
   * Token usage consumed inside the tool execution itself (e.g. nested LLM
   * calls from `delegate_to_agent`). Accumulated into the parent runner's
   * total so budgets/cost tracking stay accurate across delegation.
   */
  readonly tokenUsage?: TokenUsage
  /** Per-call gate decision, if an onToolCall hook evaluated this tool call. */
  readonly toolCallGate?: ToolCallGateMetadata
}

/** Value returned by a tool's `execute` function. */
export interface ToolResult {
  readonly data: string
  readonly isError?: boolean
  readonly metadata?: ToolResultMetadata
}

/**
 * A tool registered with the framework.
 *
 * `inputSchema` is a Zod schema used for validation before `execute` is called.
 * At API call time it is converted to JSON Schema for {@link LLMToolDef}, unless
 * `llmInputSchema` is set (e.g. MCP tools ship JSON Schema from the server).
 *
 * `outputSchema` is optional runtime validation for `ToolResult.data`.  When
 * set and validation fails, execution returns an error ToolResult instead of
 * propagating invalid output.
 */
export interface ToolDefinition<TInput = Record<string, unknown>> {
  readonly name: string
  readonly description: string
  readonly inputSchema: ZodSchema<TInput>
  /**
   * Marks a tool whose grant permits real side effects. Omitted/false means
   * benign for undeclared-run fallback classification. The runtime never
   * infers this value from prompts, tool arguments, or keywords.
   */
  readonly consequential?: boolean
  /**
   * Optional runtime validator for `ToolResult.data` (always a string).
   *
   * **Not to be confused with {@link AgentConfig.outputSchema}**, which
   * validates an agent's final JSON answer. This one only guards a single
   * tool's serialised output.
   */
  readonly outputSchema?: ZodSchema<string>
  /**
   * When present, used as {@link LLMToolDef.inputSchema} as-is instead of
   * deriving JSON Schema from `inputSchema` (Zod).
   */
  readonly llmInputSchema?: Record<string, unknown>
  /**
   * Per-tool maximum output length in characters. When set, tool output
   * exceeding this limit is truncated (head + tail with a marker in between).
   * Takes priority over {@link AgentConfig.maxToolOutputChars}.
   */
  readonly maxOutputChars?: number
  execute(input: TInput, context: ToolUseContext): Promise<ToolResult>
}

// ---------------------------------------------------------------------------
// Agent
// ---------------------------------------------------------------------------

/**
 * Extended thinking / reasoning configuration shared by {@link AgentConfig}
 * and {@link LLMChatOptions}.
 *
 * - `budgetTokens` maps to Anthropic's `thinking.budget_tokens` and Gemini's
 *   `thinkingConfig.thinkingBudget`.
 * - `effort` maps to OpenAI o-series / gpt-5 `reasoning_effort`. Carried as
 *   an explicit value rather than derived from `budgetTokens` so the call
 *   site stays unambiguous across providers.
 *
 * The `effort` union is intentionally narrowed to the values declared by
 * the pinned `openai` SDK (`'low' | 'medium' | 'high'`). Newer values
 * shipped by the API but not yet in the SDK type union (e.g. gpt-5's
 * `'minimal'`, GPT-5.5's `'none'`) should be passed via `extraBody:
 * { reasoning_effort: '<value>' }`, matching how `top_k` / `min_p` are
 * handled for vLLM.
 *
 * Adapters that don't recognise a given field ignore it.
 */
export interface ThinkingConfig {
  readonly enabled: boolean
  readonly budgetTokens?: number
  readonly effort?: 'low' | 'medium' | 'high'
}

/** Context passed to the {@link AgentConfig.beforeRun} hook. */
export interface BeforeRunHookContext {
  /** The user prompt text. */
  readonly prompt: string
  /** The agent's static configuration. */
  readonly agent: AgentConfig
}

/**
 * A minimal, SDK-agnostic view of an ACP `session/request_permission` prompt,
 * passed to a {@link AcpAgentBackendConfig.permission} callback so callers can decide
 * without importing `@agentclientprotocol/sdk`.
 */
export interface AcpPermissionRequest {
  /** Human-readable title of the pending tool call (e.g. `"Edit src/app.ts"`). */
  readonly title: string
  /** ACP tool kind when the agent provides one (e.g. `'edit'`, `'execute'`, `'read'`). */
  readonly kind?: string
  /** The option kinds the agent offered (e.g. `'allow_once'`, `'reject_always'`). */
  readonly optionKinds: readonly string[]
}

/**
 * How an ACP-backed agent answers a permission prompt. OMA runs agents
 * autonomously inside a task DAG, so the default is `'auto-approve'`.
 *  - `'auto-approve'` — select an `allow_*` option, preferring the least-privilege
 *    `allow_once` over a session-wide `allow_always` (falls back to cancel).
 *  - `'reject'` — select a `reject_*` option, preferring `reject_once` (falls back to cancel).
 *  - function — decide per request; `true` approves, `false` rejects.
 */
export type AcpPermissionPolicy =
  | 'auto-approve'
  | 'reject'
  | ((request: AcpPermissionRequest) => boolean | Promise<boolean>)

/**
 * Configuration for running an external agent over the Agent Client Protocol
 * (ACP) as an OMA team member — see {@link AgentConfig.backend}. The agent is a
 * local subprocess (a coding CLI such as Gemini CLI or Claude Code) that runs its
 * own agentic loop, while OMA drives it, collects its output and token usage, and
 * schedules it in the task DAG alongside LLM agents.
 *
 * Requires the optional peer `@agentclientprotocol/sdk`.
 */
export interface AgentBackendConfig {
  /** Backend discriminant. */
  readonly kind: 'acp'
  /** Executable to spawn (e.g. `'npx'`, `'gemini'`, `'codex-acp'`). */
  readonly command: string
  /** Arguments passed to `command` (e.g. `['-y', '@agentclientprotocol/claude-agent-acp']`). */
  readonly args?: readonly string[]
  /** Extra environment variables for the subprocess, merged over `process.env`. */
  readonly env?: Readonly<Record<string, string>>
  /**
   * Working directory the agent reads and edits. Defaults to `process.cwd()`.
   * Unlike OMA's filesystem-tool sandbox, an ACP agent accesses this directory
   * directly — scope it to a project you trust the external agent with.
   */
  readonly cwd?: string
  /** How to answer the agent's permission prompts. Defaults to `'auto-approve'`. */
  readonly permission?: AcpPermissionPolicy
}

/** Alias for the ACP backend config; `AgentBackendConfig` is kept for v1.10 compatibility. */
export interface AcpAgentBackendConfig extends AgentBackendConfig {}

/** How a generic process backend receives a prompt. */
export type ProcessBackendInputMode = 'stdin' | 'argument' | 'none'

/**
 * Configuration for running a generic local process as an OMA team member.
 *
 * Unlike ACP, this backend does not speak an agent protocol. It starts a fresh
 * process per run, sends the prompt by stdin or final argument, maps stdout to
 * the agent output, and treats non-zero exits as task failures.
 */
export interface ProcessAgentBackendConfig {
  /** Backend discriminant. */
  readonly kind: 'process'
  /** Executable to spawn (e.g. `'node'`, `'python'`, `'my-cli'`). */
  readonly command: string
  /** Arguments passed to `command` before the prompt argument, if any. */
  readonly args?: readonly string[]
  /** Extra environment variables for the subprocess, merged over `process.env`. */
  readonly env?: Readonly<Record<string, string>>
  /** Working directory for the subprocess. Defaults to `process.cwd()`. */
  readonly cwd?: string
  /**
   * Prompt delivery mode. Defaults to `'stdin'`.
   * - `'stdin'`: write the prompt to stdin and close it.
   * - `'argument'`: append the prompt as the final command argument.
   * - `'none'`: do not send the prompt; useful for fixed command adapters.
   */
  readonly input?: ProcessBackendInputMode
}

/** External backend configuration keyed by `kind`. */
export type ExternalAgentBackendConfig = AgentBackendConfig | ProcessAgentBackendConfig

/** Static configuration for a single agent. */
export interface AgentConfig {
  readonly name: string
  /**
   * Model identifier (e.g. `'claude-opus-4-6'`).
   *
   * Optional in an orchestrated run: under `runTeam` / `runTasks` / `runAgent`
   * an unset model inherits {@link OrchestratorConfig.defaultModel} (mirroring
   * how `provider` / `baseURL` / `apiKey` inherit their `default*` siblings).
   * A standalone `new Agent(...)` has no orchestrator to inherit from, so it
   * must set this explicitly — the constructor throws when it is absent.
   */
  readonly model?: string
  /**
   * Optional custom {@link LLMAdapter}. When set, the agent uses this adapter
   * directly and skips {@link createAdapter} — `provider`, `apiKey`, `baseURL`,
   * and `region` are ignored for LLM calls.
   */
  readonly adapter?: LLMAdapter
  /**
   * Run this agent on an external {@link ExternalAgentBackendConfig} instead of
   * an LLM adapter. When set, the
   * LLM-specific fields (`model`, `provider`, `adapter`, sampling, tools, context
   * strategy) do not apply — the external agent runs its own loop — but the agent
   * still participates in the task DAG, shared memory, cascade-on-failure, and
   * token budget like any other team member. ACP backends require the optional
   * peer `@agentclientprotocol/sdk`; generic process backends use Node child
   * processes and do not require an optional peer.
   */
  readonly backend?: ExternalAgentBackendConfig
  readonly provider?: SupportedProvider
  /**
   * Custom base URL for OpenAI-compatible APIs (Ollama, vLLM, LM Studio, etc.).
   * Note: local servers that don't require auth still need `apiKey` set to a
   * non-empty placeholder (e.g. `'ollama'`) because the OpenAI SDK validates it.
   */
  readonly baseURL?: string
  /** API key override; falls back to the provider's standard env var. */
  readonly apiKey?: string
  /** AWS region override for the `bedrock` provider; falls back to `AWS_REGION` env var, then `'us-east-1'`. Ignored by all other providers. */
  readonly region?: string
  readonly systemPrompt?: string
  /**
   * Custom tool definitions to register alongside built-in tools.
   * Created via `defineTool()`. Custom tools bypass `tools` (allowlist)
   * and `toolPreset` filtering, but can still be blocked by `disallowedTools`.
   *
   * Tool names must not collide with built-in tool names; a duplicate name
   * will throw at registration time.
   */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  readonly customTools?: readonly ToolDefinition<any>[]
  /** Names of tools (from the tool registry) available to this agent. */
  readonly tools?: readonly string[]
  /** Names of tools explicitly disallowed for this agent. */
  readonly disallowedTools?: readonly string[]
  /**
   * Optional per-call tool gate. Called after tool input validates and before
   * execution. Return `{ action: 'deny' }` to surface an error ToolResult to the
   * model without throwing or invoking the tool implementation.
   */
  readonly onToolCall?: ToolCallGate
  /** Predefined tool preset for common use cases. */
  readonly toolPreset?: 'readonly' | 'readwrite' | 'full'
  /**
   * Per-agent scoped secrets made available to tool code via
   * {@link ToolUseContext.credentials}. Give each agent only the credentials
   * it needs (e.g. a `researcher` gets a search-API key, a `publisher` gets a
   * CMS token) instead of closing a single shared secret over every tool.
   * Never merged across agents and never inherited from the coordinator: an
   * agent holds exactly the bag set here, or none.
   *
   * A scoping convenience, not a sandbox — tool code runs in-process and can
   * still read `process.env`. Values are treated as secrets: the `credentials`
   * key is auto-redacted from traces and dashboards.
   */
  readonly credentials?: Readonly<Record<string, string>>
  /**
   * Root directory used by built-in filesystem tools (`file_read`,
   * `file_write`, `file_edit`, `grep`, `glob`). Paths must be absolute and
   * resolve inside this directory; symlinks are resolved before the check.
   *
   * Defaults to {@link OrchestratorConfig.defaultCwd} (or
   * `<process.cwd()>/.agent-workspace` if neither is set). Pass `null` to
   * disable the sandbox for this agent.
   */
  readonly cwd?: string | null
  readonly maxTurns?: number
  readonly maxTokens?: number
  /** Maximum cumulative tokens (input + output) allowed for this run. */
  readonly maxTokenBudget?: number
  /** Optional context compression policy to control input growth across turns. */
  readonly contextStrategy?: ContextStrategy
  readonly temperature?: number
  /**
   * OpenAI-track sampling penalty for token frequency. Forwarded to OpenAI
   * cloud and OpenAI-compatible local servers (vLLM, llama-server). The
   * Anthropic adapter ignores this field.
   */
  readonly frequencyPenalty?: number
  /**
   * OpenAI-track sampling penalty for token presence. Forwarded to OpenAI
   * cloud and OpenAI-compatible local servers. The Anthropic adapter
   * ignores this field.
   */
  readonly presencePenalty?: number
  /**
   * Nucleus sampling cutoff. Forwarded to all adapters (OpenAI cloud,
   * OpenAI-compatible local, Anthropic).
   */
  readonly topP?: number
  /**
   * Top-k sampling cutoff. Forwarded to Anthropic and OpenAI-compatible
   * local servers. Cloud OpenAI rejects this parameter.
   */
  readonly topK?: number
  /**
   * Min-p sampling cutoff. Only supported by OpenAI-compatible local
   * servers (vLLM, llama-server, etc.). Cloud OpenAI rejects this parameter
   * and the Anthropic adapter ignores it.
   */
  readonly minP?: number
  /**
   * Whether the model may emit multiple tool calls in a single assistant
   * turn. Forwarded to OpenAI cloud and OpenAI-compatible local servers as
   * `parallel_tool_calls`. The Anthropic adapter ignores this field.
   *
   * - `undefined` (default): omit the field, server default applies. Cloud
   *   OpenAI defaults to `true`.
   * - `false`: force serial tool calling. Required by some local servers
   *   (vLLM, llama-server, certain quantized setups) that truncate
   *   concurrent `tool_call` deltas during streaming or return malformed
   *   `tool_calls` when more than one is emitted.
   * - `true`: explicit opt-in (matches the cloud default; no behavior
   *   change for cloud OpenAI users).
   */
  readonly parallelToolCalls?: boolean
  /**
   * Adapter-specific escape hatch merged into the outgoing request payload.
   * Spread between the sampling params and the structural fields, so values
   * here can override the standard sampling defaults (`temperature`, `topP`,
   * etc.) but cannot override transport-level fields (`model`, `messages`,
   * `tools`, `stream`, and Anthropic's `system`).
   */
  readonly extraBody?: Record<string, unknown>
  /**
   * Extended thinking / reasoning configuration. Provider mapping:
   * - Anthropic: forwards `enabled` + `budgetTokens` as the `thinking` request
   *   param (see `toAnthropicThinkingParam`).
   * - Gemini: forwards `enabled` + `budgetTokens` as `thinkingConfig`
   *   (`includeThoughts` defaults on when enabled).
   * - OpenAI: forwards `effort` as `reasoning_effort` (o-series, gpt-5).
   *   The `enabled`/`budgetTokens` fields are ignored — OpenAI's reasoning
   *   surface is qualitative (`effort`), not quantitative.
   * - All other providers (Bedrock, local servers, etc.): ignored. Use
   *   {@link extraBody} for provider-specific reasoning controls instead.
   */
  readonly thinking?: ThinkingConfig
  /**
   * Maximum wall-clock time (in milliseconds) for the entire agent run.
   * When exceeded, the run is aborted via `AbortSignal.timeout()`.
   * Useful for local models where inference can be unpredictably slow.
   */
  readonly timeoutMs?: number
  /**
   * Maximum wall-clock time (in milliseconds) for a **single** LLM call
   * (one `adapter.chat()` request), re-armed fresh for every model call the
   * agent makes. Unset (the default) leaves each call bound only by the vendor
   * SDK's own request timeout, which is inconsistent across providers and
   * absent for some (a stalled provider can then hang the whole run).
   *
   * When set, OMA merges an `AbortSignal.timeout()` into each call so the bound
   * is uniform across every adapter and composes with {@link timeoutMs} (the
   * whole-run bound) — whichever fires first wins. A per-call timeout surfaces
   * as an {@link LLMCallTimeoutError}, distinct from a caller `abortSignal`
   * cancellation. Because OMA calls the model non-streaming internally, this is
   * a wall-clock deadline over the entire response, so keep it generous for
   * slow local models or large reasoning outputs.
   */
  readonly callTimeoutMs?: number
  /**
   * Loop detection configuration. When set, the agent tracks repeated tool
   * calls and text outputs to detect stuck loops before `maxTurns` is reached.
   */
  readonly loopDetection?: LoopDetectionConfig
  /**
   * Maximum tool output length in characters for all tools used by this agent.
   * When set, tool outputs exceeding this limit are truncated (head + tail
   * with a marker in between). Per-tool {@link ToolDefinition.maxOutputChars}
   * takes priority over this value.
   */
  readonly maxToolOutputChars?: number
  /**
   * Compress tool results that the agent has already processed.
   *
   * In multi-turn runs, tool results persist in the conversation even after the
   * agent has acted on them. When enabled, consumed tool results (those followed
   * by an assistant response) are replaced with a short marker before the next
   * LLM call, freeing context budget for new reasoning.
   *
   * - `true` — enable with default threshold (500 chars)
   * - `{ minChars: N }` — only compress results longer than N characters
   * - `false` / `undefined` — disabled (default)
   *
   * Error tool results are never compressed.
   */
  readonly compressToolResults?: boolean | { readonly minChars?: number }
  /**
   * Opt-in: when an outbound IR-to-native conversion encounters a
   * {@link ReasoningBlock} that the target adapter cannot natively echo
   * (see {@link LLMAdapter.capabilities.echoesReasoning}), downgrade the
   * block to `<thinking>...</thinking>` text and prepend to the next text
   * part instead of dropping it silently (today's default).
   *
   * Triggers in two scenarios:
   *  1. **Same-provider replay** through a `'never'` adapter (e.g. an
   *     OpenAI o-series response carries `reasoning_content` that gets
   *     extracted to a `ReasoningBlock`; on the next turn it would
   *     normally be dropped because Chat Completions doesn't accept
   *     reasoning input).
   *  2. **Cross-provider handoff** — `Agent.prompt()` switching `model`
   *     mid-conversation, or any other path that puts a block from one
   *     provider in front of another adapter.
   *
   * Default `false` because enabling silently inflates prompt tokens
   * (reasoning blocks can be very long) and emits the model's internal
   * thinking text to potentially different providers, both of which the
   * user should consent to. See #223 for the design discussion.
   *
   * Caveat: some OpenAI-compatible local models echo `<thinking>` text
   * back as if it were instruction, which can trip the loop detector —
   * see `examples/patterns/cross-provider-reasoning.ts`.
   */
  readonly preserveReasoningAsText?: boolean
  /**
   * Truncate the inner text of each `<thinking>` block emitted by the
   * {@link preserveReasoningAsText} fallback. Shares the
   * `boolean | { minChars?: number }` shape with
   * {@link compressToolResults}, but **the compression method differs**:
   *
   *   - `compressToolResults`: blocks over the threshold are *replaced*
   *     wholesale with a short marker string.
   *   - `compressReasoningText`: blocks over the threshold are kept but
   *     reduced to a head+tail excerpt that fits within `minChars`. The
   *     same number serves as both the activation threshold AND the cap on
   *     the post-truncation length.
   *
   * Values:
   * - `true` — enable with default 1200-char head+tail excerpt.
   * - `{ minChars: N }` — pass blocks of length ≤ N untouched; truncate
   *   longer blocks to fit within N chars.
   * - `false` — never truncate (footgun for long CoT, not recommended).
   * - `undefined` — defaults to `true` when {@link preserveReasoningAsText}
   *   is `true`, else `false`. Matches the maintainer's guidance in #223
   *   to "tie compress default-on to the preserve flag".
   *
   * Has no effect when {@link preserveReasoningAsText} is `false` (no
   * fallback runs, so nothing to truncate).
   */
  readonly compressReasoningText?: boolean | { readonly minChars?: number }
  /**
   * Optional Zod schema for structured output.  When set, the agent's final
   * output is parsed as JSON and validated against this schema.  A single
   * retry with error feedback is attempted on validation failure.
   *
   * **Distinct from {@link ToolDefinition.outputSchema}**, which validates an
   * individual tool's `ToolResult.data` string. This one operates on the
   * agent's final answer as parsed JSON.
   */
  readonly outputSchema?: ZodSchema
  /**
   * Called before each agent run. Receives the prompt and agent config.
   * Return a (possibly modified) context to continue, or throw to abort the run.
   * Only `prompt` from the returned context is applied; `agent` is read-only informational.
   */
  readonly beforeRun?: (context: BeforeRunHookContext) => Promise<BeforeRunHookContext> | BeforeRunHookContext
  /**
   * Called after each agent run completes successfully. Receives the run result.
   * Return a (possibly modified) result, or throw to mark the run as failed.
   * Not called when the run throws. For error observation, handle errors at the call site.
   */
  readonly afterRun?: (result: AgentRunResult) => Promise<AgentRunResult> | AgentRunResult
}

// ---------------------------------------------------------------------------
// Loop detection
// ---------------------------------------------------------------------------

/** Configuration for agent loop detection. */
export interface LoopDetectionConfig {
  /**
   * Maximum consecutive times the same tool call (name + args) or text
   * output can repeat before detection triggers. Default: `3`.
   */
  readonly maxRepetitions?: number
  /**
   * Number of recent turns to track for repetition analysis. Default: `4`.
   */
  readonly loopDetectionWindow?: number
  /**
   * Action to take when a loop is detected.
   * - `'warn'`      — inject a "you appear stuck" message, give the LLM one
   *                    more chance; terminate if the loop persists (default)
   * - `'terminate'` — stop the run immediately
   * - `function`    — custom callback (sync or async); return `'continue'`,
   *                    `'inject'`, or `'terminate'` to control the outcome
   */
  readonly onLoopDetected?: 'warn' | 'terminate' | ((info: LoopDetectionInfo) => 'continue' | 'inject' | 'terminate' | Promise<'continue' | 'inject' | 'terminate'>)
}

/** Diagnostic payload emitted when a loop is detected. */
export interface LoopDetectionInfo {
  readonly kind: 'tool_repetition' | 'text_repetition'
  /** Number of consecutive identical occurrences observed. */
  readonly repetitions: number
  /** Human-readable description of the detected loop. */
  readonly detail: string
}

/** Lifecycle state tracked during an agent run. */
export interface AgentState {
  status: 'idle' | 'running' | 'completed' | 'error'
  messages: LLMMessage[]
  tokenUsage: TokenUsage
  error?: Error
}

/** A single recorded tool invocation within a run. */
export interface ToolCallRecord {
  readonly toolName: string
  readonly input: Record<string, unknown>
  readonly output: string
  /** Wall-clock duration in milliseconds. */
  readonly duration: number
}

/** The final result produced when an agent run completes (or fails). */
export interface AgentRunResult extends RunOutcomeFields {
  readonly success: boolean
  readonly output: string
  readonly messages: LLMMessage[]
  readonly tokenUsage: TokenUsage
  readonly toolCalls: ToolCallRecord[]
  /**
   * Parsed and validated structured output when `outputSchema` is set on the
   * agent config.  `undefined` when no schema is configured or validation
   * failed after retry.
   */
  readonly structured?: unknown
  /** True when the run was terminated or warned due to loop detection. */
  readonly loopDetected?: boolean
  /** True when the run stopped because token budget was exceeded. */
  readonly budgetExceeded?: boolean
  /**
   * The underlying thrown error when `success` is false due to an exception
   * (e.g. a provider `APIError` carrying `.status`), preserved so retry logic
   * can classify it as retryable vs terminal. `undefined` for app-level
   * failures. In-process only — collapses to `{}` if the result is
   * JSON-serialized.
   */
  readonly error?: unknown
}

// ---------------------------------------------------------------------------
// Team
// ---------------------------------------------------------------------------

/** Static configuration for a team of cooperating agents. */
export interface TeamConfig {
  readonly name: string
  readonly agents: readonly AgentConfig[]
  readonly sharedMemory?: boolean
  /**
   * Custom {@link MemoryStore} backing the team's shared memory (e.g. Redis,
   * Postgres, or a remote service). When provided, shared memory is enabled
   * regardless of `sharedMemory`. When both are set, `sharedMemoryStore` wins.
   * When omitted and `sharedMemory` is `true`, the default in-memory store is used.
   *
   * SDK-only: the CLI (`oma`) cannot pass runtime objects through its JSON config.
   */
  readonly sharedMemoryStore?: MemoryStore
  readonly maxConcurrency?: number
}

/** Model/provider/API-key override selected by a model routing rule. */
export interface ModelRouteConfig {
  /** Model selected for the matched run. */
  readonly model: string
  /** Provider selected for the matched run. Defaults to the agent's provider/default provider when omitted. */
  readonly provider?: SupportedProvider
  /** Custom base URL for OpenAI-compatible or self-hosted endpoints. */
  readonly baseURL?: string
  /** API key selected for the matched run. */
  readonly apiKey?: string
  /** AWS region selected for Bedrock routes. */
  readonly region?: string
  /**
   * Ordered fallback routes to try on retryable provider errors.
   *
   * The first entry becomes active on the next retry after the primary route
   * fails; later retries advance through the list in order. Empty by default.
   */
  readonly fallback?: readonly ModelRouteConfig[]
}

/** Deterministic, predicate-free route selector for a model routing rule. */
export interface ModelRoutingMatch {
  /** Orchestration phase to match. */
  readonly phase?: 'coordinator' | 'synthesis' | 'short-circuit' | 'worker' | 'delegated'
  /** Agent name to match. */
  readonly agent?: string
  /** Task role to match, supplied by explicit tasks or coordinator JSON. */
  readonly taskRole?: string
  /** Task priority to match, supplied by explicit tasks or coordinator JSON. */
  readonly taskPriority?: 'low' | 'normal' | 'high' | 'critical'
  /** Match tasks that have no dependents in the current execution graph. */
  readonly leaf?: boolean
  /** Match tasks that depend on one or more prior tasks. */
  readonly hasDependencies?: boolean
}

/** A single deterministic model routing rule. Rules are evaluated in array order; first match wins. */
export interface ModelRoutingRule {
  readonly match: ModelRoutingMatch
  readonly route: ModelRouteConfig
}

/** Opt-in, deterministic model routing policy for team orchestration calls. */
export interface ModelRoutingPolicy {
  readonly rules: readonly ModelRoutingRule[]
}

/** Input task descriptor accepted by {@link OpenMultiAgent.runTasks}. */
export interface RunTaskSpec {
  readonly title: string
  readonly description: string
  readonly assignee?: string
  readonly dependsOn?: string[]
  readonly memoryScope?: 'dependencies' | 'all'
  readonly maxRetries?: number
  readonly retryDelayMs?: number
  readonly retryBackoff?: number
  readonly role?: string
  readonly priority?: 'low' | 'normal' | 'high' | 'critical'
  readonly verify?: ConsensusVerifyOptions
}

/** Per-call options for {@link OpenMultiAgent.runTasks}. */
export interface RunTasksOptions extends RunIdentityOptions {
  readonly abortSignal?: AbortSignal
  /**
   * Optional per-run token ceiling. When an orchestrator-level
   * {@link OrchestratorConfig.maxTokenBudget} is also set, the lower ceiling
   * wins. Enforcement reuses the existing turn/task-boundary accounting.
   */
  readonly maxTokenBudget?: number
  /**
   * Optional per-run cost ceiling in the application-defined cost unit. When
   * an orchestrator-level {@link OrchestratorConfig.maxCostBudget} is also set,
   * the lower ceiling wins. Requires {@link OrchestratorConfig.estimateCost}.
   */
  readonly maxCostBudget?: number
  /**
   * Opt-in durable task checkpointing. When enabled, the orchestrator writes a
   * checkpoint after each successfully completed task using the configured
   * {@link MemoryStore}. Defaults to off.
   *
   * `true` uses the team's shared-memory store when available, otherwise a
   * private in-memory store for the run. Pass an object to provide a durable
   * store or custom key/run id.
   */
  readonly checkpoint?: boolean | CheckpointOptions
  /**
   * Opt-in deterministic model routing. When omitted, existing agent and
   * coordinator model selection is unchanged.
   */
  readonly modelRouting?: ModelRoutingPolicy
}

/**
 * A privacy-preserving roster entry supplied to an {@link ExecutionRouter}.
 *
 * This is intentionally smaller than {@link AgentConfig}: in particular it
 * never contains `systemPrompt`. A later capability model may add structured
 * fields without exposing full prompts.
 */
export interface RosterSummaryEntry {
  readonly name: string
  readonly model: string
  /** Count of directly declared built-in and custom tools, when known. */
  readonly toolCount?: number
}

/** Budget still available when execution routing begins. */
export interface RoutingBudget {
  readonly tokenRemaining?: number
  readonly costRemaining?: number
}

/** Stable, language-neutral inputs available to an {@link ExecutionRouter}. */
export interface RoutingContext {
  readonly goal: string
  readonly roster: readonly RosterSummaryEntry[]
  readonly budget?: RoutingBudget
}

/** Explainable single-agent or team-topology decision. */
export interface RoutingDecision {
  readonly mode: 'single' | 'team'
  readonly confidence?: number
  readonly reasons: readonly string[]
  readonly routerVersion: string
}

/** Pluggable execution-topology policy for automatic `runTeam()` calls. */
export interface ExecutionRouter {
  readonly version: string
  decide(context: RoutingContext): RoutingDecision | Promise<RoutingDecision>
}

/**
 * Per-call options for {@link OpenMultiAgent.runTeam}. Differs from
 * {@link OrchestratorConfig} by being scoped to a single invocation.
 */
export interface RunTeamOptions extends RunTasksOptions {
  readonly coordinator?: CoordinatorConfig
  /**
   * Application-selected execution mode for this invocation.
   *
   * `'single'` always uses the existing best-agent path. `'team'` forces the
   * existing coordinator-generated team path and bypasses the simple-goal
   * short circuit.
   *
   * This application choice takes precedence over {@link governanceIntent}.
   * If the selected mode fails a declared `required` floor, execution is kept
   * but the result is disclosed as governance `unsatisfied` / `overridden`.
   * Selecting a mode does not count as declaring governance intent, so
   * consequential confirmation still applies when `governanceIntent` is
   * omitted.
   */
  readonly mode?: 'single' | 'team'
  /**
   * Per-run execution router override.
   *
   * Precedence is: explicit {@link mode} > declared governance policy
   * (`governanceIntent` / `preferredUnderBudget`) > this router > the
   * orchestrator's router (the built-in deterministic router by default).
   * Routers run only for automatic, non-`planOnly` topology selection and
   * never override the first two layers.
   */
  readonly executionRouter?: ExecutionRouter
  /**
   * Optional structured governance signal for this goal.
   *
   * `'required'` and `'preferred'` both bypass coordinator decomposition and
   * the simple-goal short circuit. Instead, `runTeam()` executes one task per
   * {@link requiredRoles} entry using the declared roster assignments.
   * `'none'` and an omitted value preserve the existing automatic routing
   * behavior.
   *
   * When combined with {@link planOnly}, the declared role topology is built
   * and validated but not executed; `planOnly` wins.
   */
  readonly governanceIntent?: 'required' | 'preferred' | 'none'
  /**
   * Agent names from the team roster that must execute independent tasks when
   * {@link governanceIntent} is `'required'` or `'preferred'`.
   */
  readonly requiredRoles?: readonly string[]
  /**
   * Optional execution order for {@link requiredRoles}. When provided, it must
   * be a permutation of `requiredRoles`; each role depends on the previous one.
   * When omitted, the declared role tasks have no dependencies and may run in
   * parallel.
   */
  readonly requiredOrder?: readonly string[]
  /**
   * Application policy for a `preferred` declaration when a token or cost
   * ceiling applies to the run.
   *
   * `'attempt'` (the default) preserves the existing declared-role topology.
   * `'degrade'` chooses the Single path up front and attaches the
   * `review-skipped-due-to-budget` disclosure flag. It does not predict model
   * cost or attempt a pre-run fit estimate.
   */
  readonly preferredUnderBudget?: 'attempt' | 'degrade'
  /**
   * When true, returns a validated plan without running task agents. The
   * returned {@link TeamRunResult} has `planOnly: true`, `success: true`, and
   * `tasks` populated (all `pending`, no metrics).
   *
   * With `governanceIntent: 'required' | 'preferred'`, no coordinator or task
   * agent runs; the validated declared-role topology is returned instead, and
   * `governanceConclusion` is `'not-applicable'`. Otherwise, `planOnly`
   * bypasses the simple-goal short circuit and runs only the coordinator
   * decomposition call, which is reflected in `agentResults` and token usage.
   *
   * For coordinator-generated plans, if {@link OrchestratorConfig.onPlanReady}
   * is wired up and returns false, the rejection wins: result is
   * `success: false` and `planOnly` is undefined.
   */
  readonly planOnly?: boolean
  /**
   * When true, prepends a team-context block (original goal, full roster, and
   * this worker's assignee identity) to every worker prompt under `runTeam`.
   * Helps workers stay aligned with the overall goal and makes multi-step runs
   * easier to debug.
   *
   * Default: `false` — worker prompts are byte-identical to today.
   *
   * Scope: `runTeam` only. `runTasks` (no goal concept) and the short-circuit
   * single-agent path (no coordinator) ignore this option.
   */
  readonly revealCoordinator?: boolean
  /**
   * Opt-in deterministic model routing. When omitted, existing agent and
   * coordinator model selection is unchanged.
   */
  readonly modelRouting?: ModelRoutingPolicy
  /**
   * Judge roster for coordinator-generated task verification.
   *
   * When set, the coordinator can opt individual tasks into the `verify` hook
   * by emitting `"verify": true` (or a partial config with `mode`, `quorum`,
   * `maxRounds`, or `onDissent`) in the task JSON. The judges provided here
   * are merged in to form the full {@link ConsensusVerifyOptions}.
   *
   * Without this field, coordinator-generated tasks cannot use the verify hook
   * even if the coordinator emits a `verify` key — the field is ignored.
   *
   * Not applicable to `runTasks()` (which accepts full
   * {@link ConsensusVerifyOptions} with judges per task).
   */
  readonly verifyJudges?: readonly AgentConfig[]
}

/** Post-execution result of comparing required governance with execution facts. */
export type GovernanceConclusion = 'satisfied' | 'unsatisfied' | 'not-applicable'

/** Known application/budget causes for an unsatisfied governance conclusion. */
export type GovernanceUnsatisfiedReason = 'overridden' | 'budget'

/** Run-level aggregated metrics summary. */
export interface RunMetrics {
  readonly totalTokens: TokenUsage
  readonly totalRetries: number
  readonly errorCount: number
  readonly failureCount: number
  readonly completedCount: number
  readonly minTaskDurationMs?: number
  readonly maxTaskDurationMs?: number
  readonly avgTaskDurationMs?: number
  readonly totalDurationMs: number
}

/** Aggregated result for a full team run. */
export interface TeamRunResult extends RunOutcomeFields {
  readonly success: boolean
  /**
   * Explainable topology decision for automatic execution routing.
   *
   * Present on auto `runTeam()` paths. Omitted when the caller selected
   * `mode`, declared a role topology, chose governance budget degradation, or
   * requested `planOnly`.
   */
  readonly routingDecision?: RoutingDecision
  /**
   * Post-execution governance verdict for this run.
   *
   * OMA-produced results always set this field. It remains optional on the
   * interface so older serialized results and caller-created fixtures continue
   * to type-check. `success` retains its existing runtime-error semantics.
   */
  readonly governanceConclusion?: GovernanceConclusion
  /**
   * Machine-readable cause when a required governance floor is unsatisfied by
   * an explicit application override or by budget exhaustion. Omitted for a
   * satisfied/not-applicable conclusion and for other execution failures.
   */
  readonly governanceReason?: GovernanceUnsatisfiedReason
  readonly goal?: string
  readonly tasks?: readonly TaskExecutionRecord[]
  /**
   * True when the run was a plan-only invocation (`runTeam(team, goal, { planOnly: true })`).
   * The coordinator decomposed the goal but no task agents executed.
   * Undefined on normal runs and on `onPlanReady`-rejection results.
   */
  readonly planOnly?: boolean
  /** Keyed by agent name. */
  readonly agentResults: Map<string, AgentRunResult>
  readonly totalTokenUsage: TokenUsage
  /** Aggregated run-level metrics computed from per-task data. */
  readonly metrics?: RunMetrics
}

/** A single serializable task in a deterministic replay plan. */
export interface PlanTaskArtifact {
  readonly id: string
  readonly title: string
  readonly description: string
  readonly assignee?: string
  readonly dependsOn?: readonly string[]
  readonly memoryScope?: 'dependencies' | 'all'
  readonly maxRetries?: number
  readonly retryDelayMs?: number
  readonly retryBackoff?: number
}

/**
 * Serializable plan artifact that can be persisted and later replayed without
 * invoking the coordinator again.
 */
export interface PlanArtifact {
  readonly version: 1
  readonly goal?: string
  readonly tasks: readonly PlanTaskArtifact[]
}

// ---------------------------------------------------------------------------
// Consensus (proposer + judge verification)
// ---------------------------------------------------------------------------

/**
 * Judge roster and refutation-loop options shared by
 * {@link OpenMultiAgent.runConsensus} and the per-task `verify` hook. The
 * proposer is supplied separately (an agent for `runConsensus`, the task's own
 * result for the `verify` hook).
 */
export interface ConsensusVerifyOptions {
  /** Verifier roster. Judges run sequentially so quorum/budget can stop the rest. */
  readonly judges: readonly AgentConfig[]
  /** `'refute'` (default): identical skeptic framing. `'lens'`: distinct angle per judge. */
  readonly mode?: 'refute' | 'lens'
  /** Accepting judges required for consensus. Default `ceil(judges.length / 2)`. */
  readonly quorum?: number
  /** Maximum proposer↔judge rounds. Default `2`. */
  readonly maxRounds?: number
  /** Zod schema validated against each judge verdict; a failure counts as dissent. */
  readonly verdictSchema?: ZodSchema
  /** Action when a round misses quorum. Default `'revise'`. */
  readonly onDissent?: 'revise' | 'reject' | 'keep'
  /** Override the default verifier prompt; a function gives per-judge framing. */
  readonly judgePrompt?: string | ((judge: string) => string)
}

/** Options for {@link OpenMultiAgent.runConsensus}. */
export interface ConsensusOptions extends ConsensusVerifyOptions, RunIdentityOptions {
  /** Proposer agent(s). An array runs all (N-best); usage counts against the parent budget. */
  readonly proposer: AgentConfig | readonly AgentConfig[]
  readonly abortSignal?: AbortSignal
}

/** Result of a consensus run (or per-task `verify` hook). */
export interface ConsensusResult extends RunOutcomeFields {
  readonly answer: string
  /** `accepted` when quorum was reached (or `onDissent: 'keep'`); else `rejected`. */
  readonly verdict: 'accepted' | 'rejected'
  /** Dissenting critiques across all rounds, prefixed with the judge name. */
  readonly dissent: string[]
  readonly rounds: number
  /** Usage attributable to consensus (proposer + judges + revisions). */
  readonly tokenUsage: TokenUsage
}

// ---------------------------------------------------------------------------
// Task
// ---------------------------------------------------------------------------

/** Valid states for a {@link Task}. */
export type TaskStatus = 'pending' | 'in_progress' | 'completed' | 'failed' | 'blocked' | 'skipped'

/**
 * Metrics shown in the team-run dashboard detail panel for a single task.
 * Mirrors execution data collected during orchestration.
 */
export interface TaskExecutionMetrics {
  readonly startMs: number
  readonly endMs: number
  readonly durationMs: number
  readonly tokenUsage: TokenUsage
  readonly toolCalls: AgentRunResult['toolCalls']
  readonly retries: number
}

/** Serializable task snapshot embedded in the static HTML dashboard. */
export interface TaskExecutionRecord {
  readonly id: string
  readonly title: string
  readonly assignee?: string
  readonly status: TaskStatus
  readonly dependsOn: readonly string[]
  readonly description?: string
  /**
   * Execution config, carried so a `planOnly` snapshot can be serialized into a
   * lossless replay artifact (see {@link PlanTaskArtifact}). Populated from the
   * task; `undefined` when the task did not set them.
   */
  readonly memoryScope?: 'dependencies' | 'all'
  readonly maxRetries?: number
  readonly retryDelayMs?: number
  readonly retryBackoff?: number
  /** Verify config attached to this task, if any. Populated in `planOnly` results for inspection. */
  readonly verify?: ConsensusVerifyOptions
  readonly metrics?: TaskExecutionMetrics
}

/** A discrete unit of work tracked by the orchestrator. */
export interface Task {
  readonly id: string
  readonly title: string
  readonly description: string
  status: TaskStatus
  /** Agent name responsible for executing this task. */
  assignee?: string
  /** IDs of tasks that must complete before this one can start. */
  dependsOn?: readonly string[]
  /**
   * Controls what prior team context is injected into this task's prompt.
   * - `dependencies` (default): only direct dependency task results
   * - `all`: full shared-memory summary
   */
  readonly memoryScope?: 'dependencies' | 'all'
  /** Caller-defined task role used by model routing rules. */
  readonly role?: string
  /** Caller-defined task priority used by model routing rules. */
  readonly priority?: 'low' | 'normal' | 'high' | 'critical'
  result?: string
  readonly createdAt: Date
  updatedAt: Date
  /** Maximum number of retry attempts on failure (default: 0 — no retry). */
  readonly maxRetries?: number
  /** Base delay in ms before the first retry (default: 1000). */
  readonly retryDelayMs?: number
  /** Exponential backoff multiplier (default: 2). */
  readonly retryBackoff?: number
  /**
   * Opt-in consensus verification of this task's result. When set, judges try
   * to refute the completed task's output; their usage counts against the same
   * parent `maxTokenBudget`. Tasks without `verify` run unchanged.
   */
  readonly verify?: ConsensusVerifyOptions
}

// ---------------------------------------------------------------------------
// Orchestrator
// ---------------------------------------------------------------------------

/**
 * Progress event emitted by the orchestrator during a run.
 *
 * **v0.3 addition:** `'task_skipped'` — consumers with exhaustive switches
 * on `type` will need to add a case for this variant.
 */
export interface OrchestratorEvent {
  readonly type:
    | 'agent_start'
    | 'agent_complete'
    | 'task_start'
    | 'task_complete'
    | 'task_skipped'
    | 'task_retry'
    | 'budget_exceeded'
    | 'message'
    | 'error'
  readonly agent?: string
  readonly task?: string
  readonly data?: unknown
}

/** Top-level configuration for the orchestrator. */
export interface OrchestratorConfig {
  readonly maxConcurrency?: number
  /**
   * Strategy used to assign unassigned tasks to team agents:
   *
   * - `'round-robin'` distributes tasks evenly in roster order; use it when
   *   agents are interchangeable.
   * - `'least-busy'` prefers the agent with the fewest active tasks; use it to
   *   balance work when task duration varies.
   * - `'capability-match'` compares task text with agent names and system
   *   prompts; use it when agents have distinct, clearly described roles.
   * - `'dependency-first'` assigns tasks that unblock the most dependents
   *   first; use it for dependency-heavy DAGs.
   *
   * Defaults to `'dependency-first'`. Explicit task assignees are preserved
   * and are never replaced by this strategy.
   */
  readonly schedulingStrategy?: SchedulingStrategy
  /**
   * Default execution-topology router for automatic `runTeam()` calls.
   *
   * Precedence is: per-call explicit mode > declared governance policy >
   * per-call router > this router > the built-in deterministic router.
   * Routing is orthogonal to {@link RunTeamOptions.modelRouting}: execution
   * routing chooses Single versus Team topology, while model routing chooses
   * models inside that topology.
   */
  readonly executionRouter?: ExecutionRouter
  /**
   * Maximum depth of `delegate_to_agent` chains from a task run (default `3`).
   * Depth is per nested delegated run, not per team.
   */
  readonly maxDelegationDepth?: number
  /** Maximum cumulative tokens (input + output) allowed per orchestrator run. */
  readonly maxTokenBudget?: number
  /**
   * Maximum estimated run cost allowed for an orchestrator-managed run.
   *
   * Requires {@link estimateCost}. The framework intentionally does not ship a
   * model price table; callers own provider-specific pricing. Checked at the
   * same turn/task boundaries as {@link maxTokenBudget}, so a run may overshoot
   * by up to one model turn and should not be treated as a cent-exact stop.
   */
  readonly maxCostBudget?: number
  /**
   * Converts incremental token usage into a caller-defined cost unit.
   *
   * Called with usage from one LLM result, not cumulative usage. Return the
   * amount to add to the run's cumulative estimated cost. The context includes
   * the effective model after defaults and model routing.
   */
  readonly estimateCost?: (
    usage: TokenUsage,
    context: CostEstimateContext,
  ) => number
  /**
   * Default model inherited by every agent that does not set its own
   * {@link AgentConfig.model} — workers, the coordinator, and consensus agents
   * alike (mirroring how {@link defaultProvider} is inherited). Defaults to
   * `'claude-opus-4-6'`. Has no effect on a standalone `new Agent(...)`, which
   * has no orchestrator to inherit from and must set `model` itself.
   */
  readonly defaultModel?: string
  readonly defaultProvider?: SupportedProvider
  readonly defaultBaseURL?: string
  readonly defaultApiKey?: string
  /**
   * Default checkpoint configuration for `runTeam`, `runTasks`, `runFromPlan`,
   * and `restore`. Per-call options override this value. Defaults to off.
   */
  readonly checkpoint?: boolean | CheckpointOptions
  /**
   * Fallback tool grant for agents that declare neither {@link AgentConfig.tools}
   * nor {@link AgentConfig.toolPreset}. Built-in tools are opt-in (default-deny):
   * an agent with no grant resolves to zero built-in tools. Set this (e.g.
   * `'full'`) to restore the pre-default-deny convenience of granting every
   * built-in tool — including the unsandboxed `bash` — to such agents in one
   * line. Per-agent `tools` / `toolPreset` always override it; it never widens
   * an agent that already declares a grant. It is not applied to the internal
   * coordinator, the final-synthesis pass, or consensus (proposer / judge)
   * agents, which run from their own configs; grant those per agent.
   */
  readonly defaultToolPreset?: 'readonly' | 'readwrite' | 'full'
  /**
   * Default root directory for built-in filesystem tools when an agent does
   * not set its own {@link AgentConfig.cwd}. Defaults to
   * `<process.cwd()>/.agent-workspace`, a sandbox subdirectory auto-created
   * on first write. Pass `process.cwd()` to widen the sandbox to the entire
   * working directory, or `null` to disable it globally (filesystem tools
   * then accept arbitrary absolute or relative paths).
   */
  readonly defaultCwd?: string | null
  readonly onProgress?: (event: OrchestratorEvent) => void
  /** Best-effort online scoring of settled top-level runs. Disabled unless configured. */
  readonly evaluation?: import('./eval/online.js').OnlineEvaluationConfig
  /** Observability v2 sinks. User code owns forceFlush/shutdown lifecycle. */
  readonly observability?: import('./observability/sink.js').ObservabilityConfig
  readonly onTrace?: (event: TraceEvent) => void | Promise<void>
  /**
   * Optional per-call tool gate inherited by agents that do not define their own
   * {@link AgentConfig.onToolCall}. This is a coordination layer, not a sandbox
   * or security boundary.
   */
  readonly onToolCall?: ToolCallGate
  /**
   * Opt in to confirmation for consequential tool calls in `runAgent()` and
   * automatic `runTeam()` runs that omit `governanceIntent`.
   *
   * When enabled, an existing `onToolCall` gate decides each consequential
   * invocation. A dynamically planned `runTeam()` may also inherit approval
   * from `onPlanReady`. Without either approval path, the tool is not executed
   * and the result carries `confirmationRequired: true`. Defaults to false.
   */
  readonly requireConsequentialConfirmation?: boolean
  /**
   * Optional approval gate called between task execution rounds.
   *
   * After a batch of tasks completes, this callback receives all
   * completed {@link Task}s from that round and the list of tasks about
   * to start next. Return `true` to continue or `false` to abort —
   * remaining tasks will be marked `'skipped'`.
   *
   * Not called when:
   * - No tasks succeeded in the round (all failed).
   * - No pending tasks remain after the round (final batch).
   *
   * **Note:** Do not mutate the {@link Task} objects passed to this
   * callback — they are live references to queue state. Mutation is
   * undefined behavior.
   */
  readonly onApproval?: (completedTasks: readonly Task[], nextTasks: readonly Task[]) => Promise<boolean>
  /**
   * Optional approval gate called once after the coordinator decomposes the
   * goal into tasks and before execution begins.
   *
   * Receives the full plan as a {@link Task} array. Return `true` to proceed
   * or `false` to abort. A thrown callback is treated as an abort.
   *
   * Only invoked by `runTeam()`. `runAgent()` and `runTasks()` are
   * unaffected. The `TeamRunResult` returned on abort still reflects the
   * coordinator's decomposition tokens.
   *
   * **Note:** Do not mutate the {@link Task} objects passed to this
   * callback. They are live references to queue state; mutation is
   * undefined behavior.
   */
  readonly onPlanReady?: (tasks: readonly Task[]) => Promise<boolean>
  /**
   * Called for each streaming event emitted by an agent during runTeam().
   * When provided, agents run in streaming mode so the TUI can receive
   * real-time text deltas and tool-call events.
   * Only invoked by runTeam(). Not called for runAgent() or runTasks().
   */
  readonly onAgentStream?: (agentName: string, event: StreamEvent) => void
}

// ---------------------------------------------------------------------------
// Checkpoint / restore
// ---------------------------------------------------------------------------

/** Configuration for opt-in checkpoint persistence. */
export interface CheckpointOptions {
  /**
   * Set to `false` to disable a default checkpoint config for a single run.
   * Omitted or `true` enables checkpointing.
   */
  readonly enabled?: boolean
  /** Durable store used for checkpoint records. Defaults to the team's shared-memory store. */
  readonly store?: MemoryStore
  /** Exact store key for the latest checkpoint. Takes precedence over `runId`. */
  readonly key?: string
  /** Logical run id used to derive a checkpoint key when `key` is omitted. */
  readonly runId?: string
}

/** Options accepted by {@link OpenMultiAgent.restore}. */
export interface RestoreOptions extends RunTasksOptions {
  /** Optional goal attached to the restored result when no checkpoint goal exists. */
  readonly goal?: string
  /**
   * Coordinator config used to re-run synthesis when resuming a `runTeam` run.
   * Re-supply the same config passed to the original `runTeam` call — the
   * checkpoint cannot persist a live {@link CoordinatorConfig.adapter}. When
   * synthesis cannot run (no usable config/credentials) or the LLM call fails,
   * restore falls back to raw per-task outputs and emits an `onProgress`
   * `synthesis_failed` event.
   */
  readonly coordinator?: CoordinatorConfig
}

/** Serializable form of a {@link MemoryEntry}. */
export interface MemoryEntrySnapshot {
  readonly key: string
  readonly value: string
  readonly metadata?: Readonly<Record<string, unknown>>
  readonly createdAt: string
  readonly expiresAtTurn?: number
}

/** Serializable form of {@link SharedMemory}. */
export interface SharedMemorySnapshot {
  readonly version: 1
  readonly turnCount: number
  readonly entries: readonly MemoryEntrySnapshot[]
}

/** Serializable form of an inter-agent message. */
export interface MessageSnapshot {
  readonly id: string
  readonly from: string
  readonly to: string
  readonly content: string
  readonly timestamp: string
}

/** Serializable read-state for one agent on the MessageBus. */
export interface MessageReadStateSnapshot {
  readonly agentName: string
  readonly messageIds: readonly string[]
}

/** Serializable form of MessageBus state. Runtime subscribers are not persisted. */
export interface MessageBusSnapshot {
  readonly version: 1
  readonly messages: readonly MessageSnapshot[]
  readonly readState: readonly MessageReadStateSnapshot[]
}

/** Serializable form of a {@link Task}. */
export interface TaskSnapshot {
  readonly id: string
  readonly title: string
  readonly description: string
  readonly status: TaskStatus
  readonly assignee?: string
  readonly dependsOn?: readonly string[]
  readonly memoryScope?: 'dependencies' | 'all'
  readonly role?: string
  readonly priority?: 'low' | 'normal' | 'high' | 'critical'
  readonly result?: string
  readonly createdAt: string
  readonly updatedAt: string
  readonly maxRetries?: number
  readonly retryDelayMs?: number
  readonly retryBackoff?: number
}

/** Serializable state of a {@link TaskQueue}. */
export interface TaskQueueSnapshot {
  readonly version: 1
  readonly tasks: readonly TaskSnapshot[]
  readonly pending: readonly string[]
  readonly inProgress: readonly string[]
  readonly completed: readonly string[]
  readonly failed: readonly string[]
  readonly blocked: readonly string[]
  readonly skipped: readonly string[]
}

/** Result recorded for a completed task inside a checkpoint. */
export interface CompletedTaskCheckpoint {
  readonly taskId: string
  readonly assignee?: string
  readonly result?: string
}

interface CheckpointSnapshotBase {
  readonly mode: 'runTeam' | 'runTasks'
  readonly createdAt: string
  /** Validated per-run metadata inherited by future restore attempts. */
  readonly metadata?: Readonly<Record<string, TraceAttributeValue>>
  readonly goal?: string
  readonly queue: TaskQueueSnapshot
  readonly sharedMemory?: SharedMemorySnapshot
  readonly messageBus?: MessageBusSnapshot
  /**
   * Shared-memory turn counter at checkpoint time. Persisted separately from
   * {@link sharedMemory} so TTL/expiry stays correct on resume even when the
   * full entry snapshot is omitted (checkpoint store === shared-memory store).
   */
  readonly turnCount?: number
  readonly completedTaskResults: readonly CompletedTaskCheckpoint[]
}

/** Legacy checkpoint schema, retained for read compatibility. */
export interface CheckpointSnapshotV1 extends CheckpointSnapshotBase {
  readonly version: 1
  readonly runId?: string
}

/** Identity persisted by checkpoint schema v2. */
export interface CheckpointRunIdentity {
  readonly runId: string
  readonly attempt: number
  readonly lastTraceId: string
  readonly lastRootSpanId: string
}

/** Current checkpoint schema. */
export interface CheckpointSnapshotV2 extends CheckpointSnapshotBase {
  readonly version: 2
  readonly identity: CheckpointRunIdentity
}

/** Full persisted checkpoint for a task-based run. */
export type CheckpointSnapshot = CheckpointSnapshotV1 | CheckpointSnapshotV2

/**
 * Optional overrides for the temporary coordinator agent created by `runTeam`.
 *
 * All fields are optional. Unset fields fall back to orchestrator defaults
 * (or coordinator built-in defaults where applicable).
 */
export interface CoordinatorConfig {
  /** Coordinator model. Defaults to `OrchestratorConfig.defaultModel`. */
  readonly model?: string
  /**
   * Optional {@link LLMAdapter} for the coordinator agent. When set, coordinator
   * LLM calls use this adapter and ignore `provider` / `apiKey` / `baseURL`.
   */
  readonly adapter?: LLMAdapter
  readonly provider?: SupportedProvider
  readonly baseURL?: string
  readonly apiKey?: string
  /**
   * Full system prompt override. When set, this replaces the default
   * coordinator preamble and decomposition guidance.
   *
   * Team roster, output format, and synthesis sections are still appended.
   */
  readonly systemPrompt?: string
  /**
   * Additional instructions appended to the default coordinator prompt.
   * Ignored when `systemPrompt` is provided.
   */
  readonly instructions?: string
  readonly maxTurns?: number
  readonly maxTokens?: number
  readonly temperature?: number
  /** See {@link AgentConfig.frequencyPenalty}. */
  readonly frequencyPenalty?: number
  /** See {@link AgentConfig.presencePenalty}. */
  readonly presencePenalty?: number
  /** See {@link AgentConfig.topP}. */
  readonly topP?: number
  /** See {@link AgentConfig.topK}. */
  readonly topK?: number
  /** See {@link AgentConfig.minP}. */
  readonly minP?: number
  /** See {@link AgentConfig.parallelToolCalls}. */
  readonly parallelToolCalls?: boolean
  /**
   * Adapter-specific escape hatch merged into the outgoing request payload.
   * Spread between the sampling params and the structural fields, so values
   * here can override the standard sampling defaults (`temperature`, `topP`,
   * etc.) but cannot override transport-level fields (`model`, `messages`,
   * `tools`, `stream`, and Anthropic's `system`).
   */
  readonly extraBody?: Record<string, unknown>
  /** Predefined tool preset for common coordinator use cases. */
  readonly toolPreset?: 'readonly' | 'readwrite' | 'full'
  /** Tool names available to the coordinator. */
  readonly tools?: readonly string[]
  /** Tool names explicitly denied to the coordinator. */
  readonly disallowedTools?: readonly string[]
  /** See {@link AgentConfig.onToolCall}. */
  readonly onToolCall?: ToolCallGate
  /**
   * Root directory used by the coordinator's filesystem tools.
   * Defaults to {@link OrchestratorConfig.defaultCwd}. Pass `null` to
   * disable the sandbox for the coordinator only.
   */
  readonly cwd?: string | null
  readonly loopDetection?: LoopDetectionConfig
  readonly timeoutMs?: number
  /** See {@link AgentConfig.callTimeoutMs}. Bounds each coordinator LLM call. */
  readonly callTimeoutMs?: number
}

// ---------------------------------------------------------------------------
// Trace events — lightweight observability spans
// ---------------------------------------------------------------------------

/** Trace event type discriminants. */
export type TraceEventType =
  | 'llm_call'
  | 'tool_call'
  | 'task'
  | 'agent'
  | 'plan_ready'
  | 'agent_stream'
  | 'consensus'

/** Shared fields present on every trace event. */
export interface TraceEventBase {
  /** Unique identifier for the entire run (runTeam / runTasks / runAgent call). */
  readonly runId: string
  /** Unique identifier for this span within the run. */
  readonly spanId: string
  /** Span ID of the causal parent, when the framework can determine one. */
  readonly parentId?: string
  readonly type: TraceEventType
  /** Unix epoch ms when the span started. */
  readonly startMs: number
  /** Unix epoch ms when the span ended. */
  readonly endMs: number
  /** Wall-clock duration in milliseconds (`endMs - startMs`). */
  readonly durationMs: number
  /** Agent name associated with this span. */
  readonly agent: string
  /** Task ID associated with this span. */
  readonly taskId?: string
}

/** Emitted for each LLM API call (one per agent turn). */
export interface LLMCallTrace extends TraceEventBase {
  readonly type: 'llm_call'
  readonly model: string
  /** Distinguishes normal turn calls from context-summary calls. */
  readonly phase?: 'turn' | 'summary'
  readonly turn: number
  readonly tokens: TokenUsage
}

/** Emitted for each tool execution. */
export interface ToolCallTrace extends TraceEventBase {
  readonly type: 'tool_call'
  readonly tool: string
  readonly isError: boolean
  /** True when an onToolCall gate evaluated this tool invocation. */
  readonly gated?: boolean
  /** Decision returned by the gate, when one evaluated this call. */
  readonly gateAction?: ToolCallDecision['action']
  /** Optional denial/debug reason supplied by the gate. */
  readonly gateReason?: string
  /** The input arguments passed to the tool after best-effort sensitive-field redaction. */
  readonly input: Record<string, unknown>
  /** The serialised output returned by the tool after executor truncation and best-effort sensitive-value redaction. */
  readonly output: string
}

/** Emitted when a task completes (wraps the full retry sequence). */
export interface TaskTrace extends TraceEventBase {
  readonly type: 'task'
  readonly taskId: string
  readonly taskTitle: string
  readonly success: boolean
  readonly retries: number
}

/** Emitted when an agent run completes (wraps the full conversation loop). */
export interface AgentTrace extends TraceEventBase {
  readonly type: 'agent'
  readonly turns: number
  readonly tokens: TokenUsage
  readonly toolCalls: number
}

/** Emitted when runTeam reaches the plan approval boundary. */
export interface PlanReadyTrace extends TraceEventBase {
  readonly type: 'plan_ready'
  /** Number of tasks produced by coordinator decomposition. */
  readonly taskCount: number
  /** Approval decision returned by onPlanReady callback. */
  readonly approved: boolean
}

/** Emitted for each streaming event forwarded through onAgentStream in runTeam. */
export interface AgentStreamTrace extends TraceEventBase {
  readonly type: 'agent_stream'
  /** Underlying stream event type (`text`, `tool_use`, `done`, etc.). */
  readonly streamType: StreamEvent['type']
}

/** Emitted for each judge verdict during a consensus run. `agent` is the judge name. */
export interface ConsensusTrace extends TraceEventBase {
  readonly type: 'consensus'
  readonly round: number
  readonly accepted: boolean
  /** The judge's critique when it dissented. */
  readonly dissent?: string
}

/** Discriminated union of all trace event types. */
export type TraceEvent =
  | LLMCallTrace
  | ToolCallTrace
  | TaskTrace
  | AgentTrace
  | PlanReadyTrace
  | AgentStreamTrace
  | ConsensusTrace

// ---------------------------------------------------------------------------
// Memory
// ---------------------------------------------------------------------------

/** JSON-serializable value accepted by {@link SharedMemory}. */
export type SharedMemoryValue =
  | string
  | number
  | boolean
  | null
  | readonly SharedMemoryValue[]
  | { readonly [key: string]: SharedMemoryValue }

/** Parsed entry returned by {@link SharedMemory}; the raw {@link MemoryStore} remains string-only. */
export interface SharedMemoryEntry extends Omit<MemoryEntry, 'value'> {
  readonly value: SharedMemoryValue
}

/** Optional write-time validation for shared memory values. */
export interface SharedMemoryWriteOptions {
  readonly schema?: ZodSchema<SharedMemoryValue>
}
/** A single key-value record stored in a {@link MemoryStore}. */
export interface MemoryEntry {
  readonly key: string
  readonly value: string
  readonly metadata?: Readonly<Record<string, unknown>>
  readonly createdAt: Date
  /**
   * Optional turn-count expiry. When set, the entry is considered expired
   * once the {@link SharedMemory} turn counter reaches or exceeds this value.
   * Computed at write time as `currentTurn + ttlTurns`. Stores that don't
   * implement {@link MemoryStore.setWithExpiry} will not have this field set.
   */
  readonly expiresAtTurn?: number
}

/**
 * Persistent (or in-memory) key-value store shared across agents.
 * Implementations may be backed by Redis, SQLite, or plain objects.
 */
export interface MemoryStore {
  get(key: string): Promise<MemoryEntry | null>
  set(key: string, value: string, metadata?: Record<string, unknown>): Promise<void>
  /**
   * Optional: write an entry with a turn-count expiry. Stores that don't
   * implement this method silently lose TTL semantics — callers (e.g.
   * {@link SharedMemory}) should fall back to {@link set} and not enforce
   * expiry on entries from those backends.
   */
  setWithExpiry?(
    key: string,
    value: string,
    expiresAtTurn: number,
    metadata?: Record<string, unknown>,
  ): Promise<void>
  list(): Promise<MemoryEntry[]>
  delete(key: string): Promise<void>
  clear(): Promise<void>
}

// ---------------------------------------------------------------------------
// LLM adapter
// ---------------------------------------------------------------------------

/** Options shared by both chat and streaming calls. */
export interface LLMChatOptions {
  readonly model: string
  readonly tools?: readonly LLMToolDef[]
  readonly maxTokens?: number
  readonly temperature?: number
  /** See {@link AgentConfig.frequencyPenalty}. */
  readonly frequencyPenalty?: number
  /** See {@link AgentConfig.presencePenalty}. */
  readonly presencePenalty?: number
  /** See {@link AgentConfig.topP}. */
  readonly topP?: number
  /** See {@link AgentConfig.topK}. */
  readonly topK?: number
  /** See {@link AgentConfig.minP}. */
  readonly minP?: number
  /** See {@link AgentConfig.parallelToolCalls}. */
  readonly parallelToolCalls?: boolean
  /**
   * Adapter-specific escape hatch merged into the outgoing request payload.
   * Spread between the sampling params and the structural fields, so values
   * here can override the standard sampling defaults (`temperature`, `topP`,
   * etc.) but cannot override transport-level fields (`model`, `messages`,
   * `tools`, `stream`, and Anthropic's `system`).
   */
  readonly extraBody?: Record<string, unknown>
  /** See {@link AgentConfig.thinking}. */
  readonly thinking?: ThinkingConfig
  /** See {@link AgentConfig.preserveReasoningAsText}. */
  readonly preserveReasoningAsText?: boolean
  /** See {@link AgentConfig.compressReasoningText}. */
  readonly compressReasoningText?: boolean | { readonly minChars?: number }
  readonly systemPrompt?: string
  readonly abortSignal?: AbortSignal
}

/**
 * Options for streaming calls.
 * Extends {@link LLMChatOptions} without additional fields — the separation
 * exists so callers can type-narrow and implementations can diverge later.
 */
export interface LLMStreamOptions extends LLMChatOptions {}

/**
 * Provider-agnostic interface that every LLM backend must implement.
 *
 * @example
 * ```ts
 * const adapter: LLMAdapter = createAdapter('anthropic')
 * const response = await adapter.chat(messages, { model: 'claude-opus-4-6' })
 * ```
 */
export interface LLMAdapter {
  /** Human-readable provider name, e.g. `'anthropic'` or `'openai'`. */
  readonly name: string

  /**
   * Send a chat request and return the complete response.
   * Throws on non-retryable API errors.
   */
  chat(messages: LLMMessage[], options: LLMChatOptions): Promise<LLMResponse>

  /**
   * Send a chat request and yield {@link StreamEvent}s incrementally.
   * The final event in the sequence always has `type === 'done'` on success,
   * or `type === 'error'` on failure.
   */
  stream(messages: LLMMessage[], options: LLMStreamOptions): AsyncIterable<StreamEvent>

  /**
   * Optional declaration of how this adapter handles {@link ReasoningBlock}
   * round-tripping. Consumed by the cross-provider reasoning fallback layer
   * (see #223) to decide whether to native-echo an incoming `ReasoningBlock`
   * or downgrade it to `<thinking>` text on outbound conversion.
   *
   * - `'never'`: This adapter's wire protocol does not accept reasoning input
   *   under any circumstance (e.g. OpenAI Chat Completions). Outbound paths
   *   must fall back regardless of {@link ReasoningBlock.provenance}.
   * - `'own-issued'`: Native echo is only ever attempted when
   *   `block.provenance === this.name`. Provenance match is **necessary
   *   but not sufficient** — adapters MAY impose additional preconditions
   *   (e.g. Anthropic requires the original `signature`; Gemini drops
   *   unsigned thought summaries to keep context lean). Phase 2
   *   implementers MUST consult the adapter-specific outbound serializer
   *   for the full eligibility rule, not just the provenance match.
   * - `'tool-use-only'`: Native echo is attempted on every assistant
   *   message inside a tool-calling conversation (one that contains at
   *   least one `tool_use` block anywhere in its history), gated by
   *   `block.provenance === this.name`. This includes the final synthesis
   *   message that has no `tool_use` of its own — omitting it would 400
   *   the next user turn. Conversations with no `tool_use` anywhere skip
   *   the echo entirely (per spec, reasoning is ignored there but would
   *   still bloat context). Used by DeepSeek V4 in thinking mode.
   *
   * Omitted on third-party adapters that pre-date this field; callers treat
   * `undefined` as `'never'` to preserve today's silent-drop behaviour.
   */
  readonly capabilities?: {
    readonly echoesReasoning: 'never' | 'own-issued' | 'tool-use-only'
  }
}
